/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package estacionamiento;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandra
 */
public class Ingresar extends javax.swing.JPanel {
    private Connection con = null;
    private List<Precios> ListaPrecio = new ArrayList<>();
    private Principal principal;
    
    public void setPrincipal(Principal p){
        this.principal = p;
    }
    
    public Ingresar() {
        initComponents();
        con = ConectarBD.Conexion();
        cargarTiposVehiculo();
        establecerHoraEntrada();
    }
    
    private void establecerHoraEntrada() {
        txtH_Llegada.setText(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
        txtH_Llegada.setEditable(false);
    }
    
    @Override
    public void setVisible(boolean visible){
        super.setVisible(visible);
        if (visible) {
            establecerHoraEntrada();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPropietario = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lbPlacas = new javax.swing.JLabel();
        txtPlacas = new javax.swing.JTextField();
        lbMarca = new javax.swing.JLabel();
        cboxTipo = new javax.swing.JComboBox<>();
        btnGuardar1 = new javax.swing.JButton();
        txtColor = new javax.swing.JTextField();
        lbColor = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        txtH_Llegada = new javax.swing.JTextField();
        lbH_Llegada = new javax.swing.JLabel();
        pnTitulo = new javax.swing.JPanel();
        lbTitulo3 = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        lbDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();

        setBackground(new java.awt.Color(178, 190, 195));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(440, 410));
        setMinimumSize(new java.awt.Dimension(440, 410));
        setPreferredSize(new java.awt.Dimension(1221, 831));

        lbPropietario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbPropietario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPropietario.setText("Propietario");

        lbPlacas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbPlacas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPlacas.setText("Placas");

        lbMarca.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbMarca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMarca.setText("Marca");

        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Uno" }));

        btnGuardar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar-el-archivo.png"))); // NOI18N
        btnGuardar1.setText("Guardar ");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        txtColor.setMinimumSize(new java.awt.Dimension(64, 37));

        lbColor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbColor.setText("Color");

        btnCancelar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-x.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");

        lbH_Llegada.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbH_Llegada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbH_Llegada.setText("Hora de llegada");

        pnTitulo.setBackground(new java.awt.Color(44, 62, 80));
        pnTitulo.setPreferredSize(new java.awt.Dimension(214, 55));

        lbTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        lbTitulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        lbTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo3.setText("NUEVO AUTOMOVIL");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(637, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lbTitulo3)
                .addGap(16, 16, 16))
        );

        lbTipo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTipo.setText("Tipo de Vehiculo");

        lbDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDescripcion.setText("Descripción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(79, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbH_Llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtH_Llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(119, 119, 119)
                        .addComponent(lbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTipo))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(118, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar1)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar1)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMarca))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPropietario))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbPlacas)
                                .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(lbH_Llegada)
                    .addComponent(txtH_Llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar1)
                    .addComponent(btnGuardar1))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        txtMarca.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        insertarRegistro();
        limpiar();
    }//GEN-LAST:event_btnGuardar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JLabel lbColor;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbH_Llegada;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbPlacas;
    private javax.swing.JLabel lbPropietario;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTitulo3;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtH_Llegada;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPlacas;
    private javax.swing.JTextField txtPropietario;
    // End of variables declaration//GEN-END:variables

    
    private void cargarTiposVehiculo(){
        if(con == null){
            return;
        }
        try {
            cboxTipo.removeAllItems();
            ListaPrecio.clear();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM precios ORDER BY id_precio");
            while (rs.next()){
                Precios pr = new Precios();
                pr.setId_precio(rs.getInt("id_precio"));
                pr.setTipo(rs.getString("tipo"));
                pr.setCosto_horas(rs.getString("costo_horas"));
                pr.setDescripcion(rs.getString("descripcion"));
                ListaPrecio.add(pr);
                cboxTipo.addItem(rs.getString("tipo"));
            }
            rs.close();
            st.close();  
        }catch (Exception e){
            System.out.println("Error al cargar tipos: " + e.getMessage());
        }
    }
    
    public int getIdPrecioSeleccionado() {
        Object sel = cboxTipo.getSelectedItem();
        if (sel == null) {
            return 0;
        }

        String tipoSeleccionado = sel.toString();

        for (Precios p : ListaPrecio) {
            if (tipoSeleccionado.equals(p.getTipo())) {
                return p.getId_precio();
            }
        }
        return 0;
    }

    public void insertarRegistro(){
    try{
        Time horaEntrada = Time.valueOf(LocalTime.parse(txtH_Llegada.getText().trim(), DateTimeFormatter.ofPattern("HH:mm")));
        Automoviles au = new Automoviles(txtPropietario.getText(), txtPlacas.getText(), txtMarca.getText(), txtColor.getText(), getIdPrecioSeleccionado(), horaEntrada, txtDescripcion.getText(), true);
        String sql ="INSERT INTO automoviles(propietario, placas, marca, color, hora_llegada, descripcion, activo, id_precio) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pstmt = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        pstmt.setString(1, au.getPropietario());
        pstmt.setString(2, au.getPlacas());
        pstmt.setString(3, au.getMarca());
        pstmt.setString(4, au.getColor());
        pstmt.setTime(5, au.getHora_llegada());
        pstmt.setString(6, au.getDescripcion());
        pstmt.setBoolean(7, au.isActivo());
        pstmt.setInt(8, au.getId_precio());
        pstmt.executeUpdate();
        int idAuto = -1;
        try (java.sql.ResultSet rs = pstmt.getGeneratedKeys()) {
            if (rs.next()) {
                idAuto = rs.getInt(1);
            }
        }
        pstmt.close();
        if (idAuto > 0) {
            String tipoStr = cboxTipo.getSelectedItem() != null ? cboxTipo.getSelectedItem().toString() : "";
            String rutaPdf = GeneradorTickets.generarPreticket(idAuto, au.getPlacas(), tipoStr, txtH_Llegada.getText().trim());
            if (rutaPdf != null) {
                JOptionPane.showMessageDialog(this, "Registrado correctamente.\nPreticket guardado en: " + rutaPdf);
                GeneradorTickets.abrirPDF(rutaPdf);
            } else {
                JOptionPane.showMessageDialog(this, "Registrado correctamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Registrado Correctamente");
        } 
        if(principal != null){
            principal.volverAInicio();
        }
//        con.close();
    }catch(Exception ex){
        System.out.println(ex.getMessage());
    }
}
    
    public void limpiar(){
        txtPropietario.setText("");
        txtPlacas.setText("");
        txtMarca.setText("");
        txtColor.setText("");
        txtH_Llegada.setText("");
        txtDescripcion.setText("");
        cboxTipo.setSelectedIndex(0);     
    }



}


