/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package estacionamiento;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Alexandra
 */
public class Reportes extends javax.swing.JPanel {
    
    private JSpinner spinnerFecha;
    private JButton btnReporte1;
    private JButton btnReporte2;
    private JButton btnReporte3;
    private Connection con;

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        con = ConectarBD.Conexion();
        construirPanelReportes();

    }
    
    private void construirPanelReportes() {
        JPanel p = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 15));
        p.setBackground(getBackground());
        p.add(new JLabel("Fecha:"));
        spinnerFecha = new JSpinner(new SpinnerDateModel(new Date(), null, null, java.util.Calendar.DAY_OF_MONTH));
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy");
        spinnerFecha.setEditor(editor);
        spinnerFecha.setPreferredSize(new java.awt.Dimension(120, 28));
        p.add(spinnerFecha);

        btnReporte1 = new JButton("1. Registros terminados por día");
        btnReporte1.addActionListener(e -> generarReporte1());
        p.add(btnReporte1);

        btnReporte2 = new JButton("2. Ganancias del día");
        btnReporte2.addActionListener(e -> generarReporte2());
        p.add(btnReporte2);

        btnReporte3 = new JButton("3. Automóviles del día");
        btnReporte3.addActionListener(e -> generarReporte3());
        p.add(btnReporte3);

        p.setBounds(40, 115, 800, 50);
        add(p);
    }

    private java.sql.Date obtenerFechaSeleccionada() {
        Date d = (Date) spinnerFecha.getValue();
        return d != null ? new java.sql.Date(d.getTime()) : new java.sql.Date(System.currentTimeMillis());
    }

    private void generarReporte1() {
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No hay conexión a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ruta = Reportespdf.generarReporteRegistrosTerminados(con, obtenerFechaSeleccionada());
        if (ruta != null) {
            JOptionPane.showMessageDialog(this, "Reporte guardado en:\n" + ruta);
            GeneradorTickets.abrirPDF(ruta);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo generar el reporte.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void generarReporte2() {
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No hay conexión a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ruta = Reportespdf.generarReporteGananciasDia(con, obtenerFechaSeleccionada());
        if (ruta != null) {
            JOptionPane.showMessageDialog(this, "Reporte guardado en:\n" + ruta);
            GeneradorTickets.abrirPDF(ruta);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo generar el reporte.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void generarReporte3() {
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No hay conexión a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ruta = Reportespdf.generarReporteAutomovilesDia(con, obtenerFechaSeleccionada());
        if (ruta != null) {
            JOptionPane.showMessageDialog(this, "Reporte guardado en:\n" + ruta);
            GeneradorTickets.abrirPDF(ruta);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo generar el reporte.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        lbTitulo3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(178, 190, 195));
        setPreferredSize(new java.awt.Dimension(1221, 831));

        pnTitulo.setBackground(new java.awt.Color(44, 62, 80));
        pnTitulo.setMinimumSize(new java.awt.Dimension(1230, 90));
        pnTitulo.setPreferredSize(new java.awt.Dimension(368, 55));

        lbTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        lbTitulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        lbTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo3.setText("REPORTES");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lbTitulo3)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(721, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbTitulo3;
    private javax.swing.JPanel pnTitulo;
    // End of variables declaration//GEN-END:variables
}
