/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package estacionamiento;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Alexandra
 */
public class Salida_Automovil extends javax.swing.JPanel {
    private Connection con = null;
    private List<Precios> ListaPrecio = new ArrayList<>();
    private int idAutoActual = -1;
    private Principal principal;

    /**
     * Creates new form Salida_Automovil
     */
    public Salida_Automovil() {
        initComponents();
        con = ConectarBD.Conexion();
        cargarTiposVehiculo();
        agregarListenersCalculo();
    }
    
    private void agregarListenersCalculo() {
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { calcularTotal(); }
            @Override
            public void removeUpdate(DocumentEvent e) { calcularTotal(); }
            @Override
            public void changedUpdate(DocumentEvent e) { calcularTotal(); }
        };
        txtH_Llegada.getDocument().addDocumentListener(docListener);
        txtH_Salida.getDocument().addDocumentListener(docListener);
        cboxTipo.addItemListener(e -> calcularTotal());
    }
    
    public void setPrincipal(Principal p) {
        this.principal = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPropietario = new javax.swing.JTextField();
        lbColor = new javax.swing.JLabel();
        txtH_Salida = new javax.swing.JTextField();
        lbPropietario = new javax.swing.JLabel();
        txtH_Llegada = new javax.swing.JTextField();
        lbDescripcion = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lbH_Llegada = new javax.swing.JLabel();
        lbPlacas = new javax.swing.JLabel();
        pnTitulo = new javax.swing.JPanel();
        lbTitulo3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtPlacas = new javax.swing.JTextField();
        lbMarca = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        cboxTipo = new javax.swing.JComboBox<>();
        lbH_Salida = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        btnCargar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(178, 190, 195));
        setPreferredSize(new java.awt.Dimension(1221, 831));

        lbColor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbColor.setText("Color");

        lbPropietario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbPropietario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPropietario.setText("Propietario");

        lbDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDescripcion.setText("Descripción");

        lbH_Llegada.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbH_Llegada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbH_Llegada.setText("Hora de llegada");

        lbPlacas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbPlacas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPlacas.setText("Placas");

        pnTitulo.setBackground(new java.awt.Color(44, 62, 80));
        pnTitulo.setPreferredSize(new java.awt.Dimension(211, 55));

        lbTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        lbTitulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        lbTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo3.setText("SALIDA AUTOMOVIL");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbTitulo3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lbMarca.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbMarca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMarca.setText("Marca");

        lbTipo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTipo.setText("Tipo de Vehiculo");

        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbH_Salida.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbH_Salida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbH_Salida.setText("Hora de Salida");

        lbTotal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotal.setText("Total");

        jPanel27.setBackground(new java.awt.Color(44, 62, 80));
        jPanel27.setPreferredSize(new java.awt.Dimension(233, 55));

        btnCargar1.setBackground(new java.awt.Color(44, 62, 80));
        btnCargar1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnCargar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar1.setText("COBRAR");
        btnCargar1.setBorder(null);
        btnCargar1.setContentAreaFilled(false);
        btnCargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("$0.00");

        btnCancelar1.setBackground(new java.awt.Color(44, 62, 80));
        btnCancelar1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setText("CANCELAR");
        btnCancelar1.setBorder(null);
        btnCancelar1.setContentAreaFilled(false);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPropietario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(lbH_Salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbH_Llegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtH_Llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtH_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPropietario)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipo)
                    .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPlacas)
                    .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbH_Llegada)
                    .addComponent(txtH_Llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbH_Salida)
                    .addComponent(txtH_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbColor)
                    .addComponent(lbTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar1ActionPerformed
        guardarSalida();
        limpiar();
    }//GEN-LAST:event_btnCargar1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCargar1;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JLabel lbColor;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbH_Llegada;
    private javax.swing.JLabel lbH_Salida;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbPlacas;
    private javax.swing.JLabel lbPropietario;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTitulo3;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtH_Llegada;
    private javax.swing.JTextField txtH_Salida;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPlacas;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    
    /** Carga los tipos de vehículo desde precios (relación por PK id_precio). */
    private void cargarTiposVehiculo() {
        if (con == null) {
            return;
        }
        try {
            cboxTipo.removeAllItems();
            ListaPrecio.clear();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM precios ORDER BY id_precio");
            while (rs.next()) {
                Precios pr = new Precios();
                pr.setId_precio(rs.getInt("id_precio"));
                pr.setTipo(rs.getString("tipo"));
                pr.setCosto_horas(rs.getString("costo_horas"));
                pr.setDescripcion(rs.getString("descripcion"));
                ListaPrecio.add(pr);
                cboxTipo.addItem(rs.getString("tipo"));
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            System.out.println("Error al cargar tipos: " + e.getMessage());
        }
    }

    /** Devuelve el id_precio del tipo seleccionado (para consultas/actualizaciones). */
    public int getIdPrecioSeleccionado() {
        Object sel = cboxTipo.getSelectedItem();
        if (sel == null) {
            return 0;
        }

        String tipoSeleccionado = sel.toString();

        for (Precios p : ListaPrecio) {
            if (tipoSeleccionado.equals(p.getTipo())) {
                return p.getId_precio();
            }
        }
        return 0;
    }
    
    public void cargarDatos(Automoviles au) {
        idAutoActual = au.getId_auto();
        txtPropietario.setText(au.getPropietario() != null ? au.getPropietario() : "");
        txtPlacas.setText(au.getPlacas() != null ? au.getPlacas() : "");
        txtMarca.setText(au.getMarca() != null ? au.getMarca() : "");
        txtColor.setText(au.getColor() != null ? au.getColor() : "");
        if (au.getTipo() != null) {
            cboxTipo.setSelectedItem(au.getTipo());
        }
        txtH_Llegada.setText(au.getHora_llegadaFormato());
        txtH_Salida.setText(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
        txtDescripcion.setText(au.getDescripcion() != null ? au.getDescripcion() : "");
        calcularTotal();
    }
    
    private void guardarSalida() {
        if (idAutoActual < 0) {
            JOptionPane.showMessageDialog(this, "No hay registro cargado para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Time horaSalida = Time.valueOf(LocalTime.parse(txtH_Salida.getText().trim(), DateTimeFormatter.ofPattern("HH:mm")));
            String total = txtTotal.getText().trim();
            String descripcion = txtDescripcion.getText().trim();
            String sql = "UPDATE automoviles SET hora_salida=?, total=?, descripcion=?, activo=?  WHERE id_auto=?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setTime(1, horaSalida);
            pstmt.setString(2, total.isEmpty() ? null : total);
            pstmt.setString(3, descripcion.isEmpty() ? null : descripcion);
            pstmt.setBoolean(4, false);
            pstmt.setInt(5, idAutoActual);
            pstmt.executeUpdate();
            pstmt.close();
            String tipoStr = cboxTipo.getSelectedItem() != null ? cboxTipo.getSelectedItem().toString() : "";
            String rutaPdf = GeneradorTickets.generarTicket(idAutoActual, txtPlacas.getText().trim(), tipoStr,
                    txtH_Llegada.getText().trim(), txtH_Salida.getText().trim(), txtTotal.getText().trim());
            if (rutaPdf != null) {
                JOptionPane.showMessageDialog(this, "Salida registrada correctamente.\nTicket guardado en: " + rutaPdf);
                GeneradorTickets.abrirPDF(rutaPdf);
            } else {
                JOptionPane.showMessageDialog(this, "Salida registrada correctamente.");
            }
//            JOptionPane.showMessageDialog(this, "Salida registrada correctamente.");
            if (principal != null) {
                principal.volverAInicio();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void calcularTotal() {
        try {
            LocalTime llegada = LocalTime.parse(txtH_Llegada.getText().trim(), DateTimeFormatter.ofPattern("HH:mm"));
            LocalTime salida = LocalTime.parse(txtH_Salida.getText().trim(), DateTimeFormatter.ofPattern("HH:mm"));
            long minutos = ChronoUnit.MINUTES.between(llegada, salida);
            if (minutos < 0) {
                minutos += 24 * 60;
            }
            double horas = minutos / 60.0;

            Object tipoSel = cboxTipo.getSelectedItem();
            if (tipoSel == null) {
                txtTotal.setText("");
                jLabel1.setText("$0.00");
                return;
            }
            Precios precioTipo = null;
            for (Precios p : ListaPrecio) {
                if (p.getTipo().equals(tipoSel.toString())) {
                    precioTipo = p;
                    break;
                }
            }
            if (precioTipo == null) {
                txtTotal.setText("");
                jLabel1.setText("$0.00");
                return;
            }

            String costoStr = precioTipo.getCosto_horas().trim().replace("$", "").replace(",", ".");
            double precioPorHora = Double.parseDouble(costoStr);

            double total;
            if (horas < 1.0) {
                total = precioPorHora;
            } else {
                total = precioPorHora * horas
                        ;
            }

            String totalFormato = String.format("%.2f", total);
            txtTotal.setText(totalFormato);
            jLabel1.setText("$" + totalFormato);
        } catch (Exception e) {
            txtTotal.setText("");
            jLabel1.setText("$0.00");
        }
    }
    
    public void limpiar(){
        txtPropietario.setText("");
        txtPlacas.setText("");
        txtMarca.setText("");
        txtColor.setText("");
        txtH_Llegada.setText("");
        txtH_Salida.setText("");
        txtDescripcion.setText("");
        cboxTipo.setSelectedIndex(0);   
        txtTotal.setText("");
    }

}
